microapidev/comment-microapi

Contributions.md

This PR is an Update of the endpoints and response format document
Completed the endpoints and response format document
This will guide contributors on how to contribute and also help make the API documentation easy
Check the Contibutions.md file in the root directory
No
[Issue …

Completed the Endpoint & Response Format Document @Contributions.md

---

docs/comments.yaml
server.js

Fixes #20 
Documentation is required so that consumers of the API have a clear idea of how the API works and what is expected of them when using the API and its endpoints. This documentation pertains to the POST: /comment/create endpoint. This endpoint will be used to save new comment coming from a particular report on the web.
- Create documentation for the endpoint,
- its method,
- the required body,
- the response body,
- and the other …

[Solves #20] feat: create swagger docs for creating a new comment endpoint

---

.travis.yml

Fixes #43 
- Prepare config file for Travis
- Enable lint and testing of code on CI
- Enable auto-deployment on Heroku
- New PRs should tested and on every new commit pushed
- On merging to develop app should be available at https://comments-microservice.herokuapp.com/
This is not functional at the …

[chore]: Setup Travis for CI/CD

---

docs/comments.yaml
routes/documentation.js
server.js

Fixes #39 
Documentation is required so that consumers of the API have a clear idea of how the API works and what is expected of them when using the API and its endpoints. This PR adds the swagger the required documentation for comments.
Create documentation for all the comments endpoints.
- GET `/comments`
- POST `/comments`
- GET `/comments/refs/{refId}`
- PATCH `/comments/{commentId}`
- DELETE `/comments/{commentId}`
- PATCH …

[Solves #39] Swagger comments docs

---

__test__/root.test.js

Resolve #22
```bash
npm install
npm run test
```
example endpoint test with jest
[Issue #22 ](https://github.com/microapidev/comment-microapi/issues/22)
**Questions:**

test: add API assertions for root endpoint

---

bin/www.js
package-lock.json
package.json
server.js
utils/customError.js
utils/errorhandler.js
utils/responseHandler.js

Fixes #46 
Create a utility that allows all contributors to have a uniform response for errors and success response
- Create success response handler
- Create error response handler
- The errorHandler is used as express default error handler. Pass an error to the `next` middleware and an appropriate response object is sent in the format, message, data, status
- To send an error message create a new …

[feature]: Uniform success and error response handler

---

README.md

This PR is related to PR #56.
Adds the missing section on Endpoints Documentation.
See PR #56.
None
[Issue #54](https://github.com/microapidev/comment-microapi/issues/54)
**Questions:**
None

feat: update README to include endpoints documentation

---

middleware/validation.js
package-lock.json
package.json
routes/comments.js
server.js

Fixes #40 
Create validation middleware to be used by the Joi validation library
No routes available yet to test
All validation rules will exist in validationRules.js
[Issue #40 ](https://github.com/microapidev/comment-microapi/issues/40)
**Questions:**
If something is unclear or you want some questions to be addressed by your peers, mention them here

Ft validation mw

---

.travis.yml
README.md
__test__/api/comment-delete.test.js
__test__/api/comment-get.test.js
__test__/api/comment-post.test.js
__test__/api/index.test.js
__test__/comments.test.js
__test__/config/setup.js
__test__/helpers/conditionalTests.js
__test__/server.test.js
bin/www.js
package-lock.json
package.json
server.js

Fixes #85 
Creates function to allow jest tests to be skipped for unavailable endpoints
- Use express-list-endpoints package to pre-load all existing endpoints
- Function to check existence of given endpoint
- Function to skip jest test if endpoint not found
-  Run `npm run test` and all tests should pass including those for non-existent routes
- Appropriate message will indicate where an endpoint has …

[feature]: Create function to make tests conditional

---

docs/comments.yaml

See related issue.
See linked issue
View comments.yaml file
Not applicable
[Issue #90](https://github.com/microapidev/comment-microapi/issues/90)
**Questions:**
Not applicable

fix: update swagger docs to be in line with current code and validation rules

---

models/admins.js

Hotfix for linting error introduced while creating a commit on Github
Lint the source code by running `npm run lint:fix`
All tests should on Travis CI

[hotfix]: lint admin.js

---

__test__/api/comment-get.test.js
__test__/api/comment-post.test.js
__test__/api/index.test.js
__test__/helpers/conditionalTests.js

Resolve #102
- fix method call mismatch
- definition: `skipIfNotFound(path, method)`
- reference: `skipIfNotFound(method, path)`
- update test comment
- replace manual implementation with `skipIfNotFound`
```bash
npm install
npm run test
```
[Issue #102 ](https://github.com/microapidev/comment-microapi/issues/102)
**Questions:**

test: fix function call error

---

utils/validationRules/comments/createCommentSchema.js
utils/validationRules/index.js

Validate our request inputs on the `POST /comments` endpoint to prevent unwanted or incorrect input from being passed to the API.
Create validation rules for comment's request header and query using @hapi/joi.
The `POST /comments` endpoints needs to be implemented first.
None
[Issue …

feat: add validation rules for POST /comments

---

.github/PULL_REQUEST_TEMPLATE.md
README.md

Fixes #118 
Add contributions quick reference to README
[Issue #118](https://github.com/microapidev/comment-microapi/issues/118)

[docs]: Update README with contribution quick reference

---

__test__/api/comment-patch.test.js

TEST #119  (replace issue_number with the issue number this PR solves)
This is PR is test suite to comment the `PATCH /comments/:commentId/flag` endpoint
- Run `npm run test` in terminal
- See the output for `comment-patch.test.js`, if it passes
None
[Issue #119 …

[TEST] - PATCH /comments/{commentId}/flag

---

utils/validationRules/comments/getCommentSchema.js
utils/validationRules/index.js

Fixes #123 
The implementation to the endpoint will need to be made first.
None
[Issue #123](https://github.com/microapidev/comment-microapi/issues/123) …

feat: add validation schema for GET /comments/{commentId}

---

__test__/api/comment-delete.test.js
__test__/api/comment-get.test.js
__test__/api/comment-patch.test.js
__test__/api/comment-post.test.js
__test__/api/comment-vote.test.js
__test__/db.test.js
controller/commentsController.js
models/comments.js
models/replies.js

Fixes #131
- Removed unneeded user model field to leave user management to 3rd party applications
- Modified flags field, upvotes and downvotes fields into array of userIds
[Issue #131](https://github.com/microapidev/comment-microapi/issues/131)

[refactor]: Modify comment model

---

docs/swagger.yaml

Updates swagger docs due to updated comment and reply models.
**Summarise the main tasks handled in the pull request**
- On your terminal, run `npm start`
- On your browser, visit `localhost:4000` to view the updated swagger documentation
None
[Issue #131](https://github.com/microapidev/comment-microapi/issues/131)
**Questions:**
None

Swagger docs update

---

models/replies.js

Fix #137
Make `commentId` a required field
Change 
```javascript
commentId: {
type: mongoose.Schema.Types.ObjectId,
ref: "Comments",
}
```
To
```javascript
commentId: {
type: mongoose.Schema.Types.ObjectId,
ref: "Comments",
required: true,
}
```
```bash
npm install
npm run test
```
[Issue #137](https://github.com/microapidev/comment-microapi/issues/137)
**Questions:**

Update commentId in ReplySchema to required field

---

controller/commentsController.js

Fixes #140 
Refactors `flagComment` controller to make use of the utility response functions
- Made use of the `responseHandler` function for successful responses
- Made use of the `CustomError` class for error responses
[Issue #140](https://github.com/microapidev/comment-microapi/issues/140)

[Refactor]: Update commentController to use utils

---

__test__/api/comment-patch.test.js
__test__/helpers/conditionalTests.js

Fixes #129 
- Run in terminal `npm run test`
- Check the console for the response on `comment-patch.test.js`
[Issue #129 ](https://github.com/microapidev/comment-microapi/issues/129)
**Questions:**
If …

[TEST]: `PATCH /comments/:commentId` Fixes Issue #129

---

docs/swagger.yaml

Updates the VotedReply schema names
- Update `numVotes` to `numOfVotes`
- Update `numUpVotes` to `numOfUpVotes`
- Update `numDownVotes` to `numOfDownVotes`
- On your terminal, run `npm start`
- On your browser, visit 'localhost:4000`
None
None
**Questions:** …

fix: typo in VotedReply schema

---

controller/repliesController.js
models/replies.js
routes/replies.js

Feat: user can reply to a comment

---

__test__/api/comment-delete.test.js
controller/commentsController.js
middleware/auth.js
routes/comments.js
utils/errorhandler.js

Fixes #153 
Create dummy auth middleware to enable pass-through of authenticated routes
- Add auth middleware for application tokens [`../middleware/appAuthMW`]
- Add auth middleware for organization tokens [`../middleware/orgAuthMW`]
- Add appAuthMW middleware to a route and any sub-route will have `req.token.applicationId` property available.
Full …

feat: add dummy auth

---

controller/commentsController.js
routes/comments.js

Fixes #11 
Provides an endpoint and controller to update comment
[Issue #11](https://github.com/microapidev/comment-microapi/issues/11)

[FEATURE REQUEST]: UPDATE COMMENTS #11

---

controller/commentsController.js
utils/validationRules/comments/createCommentSchema.js
utils/validationRules/comments/getAllCommentsSchema.js
utils/validationRules/comments/updateCommentSchema.js
utils/validationRules/index.js

Fixes #151 
Controller methods need to be implemented first.
None
[Issue #151](https://github.com/microapidev/comment-microapi/issues/151)
**Questions:**
None

feat: add update comment validation schema

---

controller/commentsController.js

A hotfix for a merged linting error

[hotfix]: lint error fix

---

controller/commentsController.js
controller/repliesController.js
routes/replies.js

Fixes #157 
- Create controller method to get the reply's votes
- Create controller method to get reply votes
- Implement filtering by vote type.
- On your terminal, run `npm start`
- Using postman or similar, go get votes with endpoint (there are currently no dummy data for testing)
None
[Issue …

Get reply votes

---

controller/commentsController.js
routes/comments.js

This PR downvotes a comment. It creates a PATCH route at  /comments/{commentId}/votes/downvote
#152
Fixes #152 (replace issue_number with the issue number this PR solves)
Create controller method to downvote a comment
POSTMAN:
PATCH - /comments/{commentId}/votes/downvote
[Issue #152](https://github.com/microapidev/comment-microapi/issues/152)
**Questions:** …

[Feature Request] downvote comment endpoint

---

__test__/api/comment-post.test.js
controller/commentsController.js
routes/comments.js

Fix #52 and Fix #169 
- Create controller method to create a comment
- Fix `POST /comments` endpoint - add `applicationId` to request
Creates a new comment using the request body as described in the documentation and saves it after checking if the applicationId is in the db.
Make a post request to the /comment endpoint with a request body that matches the one in the documentation.
Give bullet point …

CommentsController - POST /comments: Create controller method to create a comment

---

controller/repliesController.js
routes/replies.js

Fixes #162 
Proposes a controller and an endpoint for downvoting a reply
[Issue #162 (https://github.com/microapidev/comment-microapi/issues/162)

[FEATURE]: User can downvote a reply

---

.env.example
.travis.yml
__test__/api/comment-get.test.js
controller/commentsController.js
controller/repliesController.js
middleware/auth.js
middleware/validation.js
package-lock.json
package.json
routes/comments.js
routes/replies.js
utils/auth/tokenGenerator.js
utils/errorhandler.js

Fixes #178 [**Breaking Changes In note**]
Create authentication middleware that parses requests for a valid token and utility to generate valid tokens
- Create separate authentication middleware for organization routes/tokens and application routes/tokens
- Add DISABLE_AUTH environment variable to temporarily disable access restriction
- Add environment variables for APP_SECRET, ORG_SECRET and JWT_SECRET for signing tokens and included in …

[feature]: Create authentication middleware

---

utils/validationRules/comments/deleteCommentSchema.js
utils/validationRules/index.js

Uses joi for validation in the delete comment controller …

Comments validation test for the dele comment controller

---

utils/validationRules/Replies/getSingleReplySchema.js

Fixes #188 (replace issue_number with the issue number this PR solves)
Create validation rules for getting a single reply's request header and params using @hapi/joi 
**What is the link …

RepliesValidationRules - GET /comments/{commentId}/replies/{replyId}: 

---

utils/validationRules/Replies/deleteReplySchema.js

Fixes #197 (replace issue_number with the issue number this PR solves)
Create validation rules for reply's request header, body, and params using @hapi/joi which would be applied when deleting a reply
n/a
n/a
[Issue #197 ](https://github.com/microapidev/comment-microapi/issues/197)
**Questions:**
If something is …

RepliesValidationRules - DELETE /comments/{commentId}/replies/{replyId}

---

utils/validationRules/Replies/updateReplySchema.js

Fixes #195 (replace issue_number with the issue number this PR solves)
Proposes validation rules for validating a PATCH request to /comments/{commentId}/replies/{replyId}
[Issue #195 ](https://github.com/microapidev/comment-microapi/issues/195)

[FEATURE]: UpdateReply Schema Validation Rules

---

utils/validationRules/Replies/getAllRepliesSchema.js

[Issue #189 ](https://github.com/microapidev/comment-microapi/issues/189)

[FEATURE REQUEST] RepliesValidationRules - GET /comments/{commentId}/replies

---

controller/commentsController.js
routes/comments.js

**ISSUE #114 ?**
[FEATURE REQUEST] "CommentsController - GET /comments: Create controller method to get all comments
I created a single configurable  route to get all comments as specified in the docs
**HOW TO TEST**
- As specified in docs, GET commente/get_comments
- All query parameters specified in docs can be used to configure the endpoint
- isFlagged, refId, origin etc.
**LINK TO GITHUB ISSUE**
[Issue #114 ](https://github.com/microapidev/comment-microapi/issues/114)
**Questions:**
**SLACK DETAILS**
- …

Issue#114_airon [FEATURE REQUEST] CommentsController - GET /comments: Create controller method to get all comments

---

__test__/api/comment-patch.test.js
__test__/config/db.js
__test__/config/setup.js
middleware/auth.js
middleware/validation.js
models/applications.js
utils/auth/tokenGenerator.js

Fixes #231 
Create global tokens and models to facilitate tests
- Add global appToken, orgToken and relevant models for use in tests
- Fix bugs in validation middleware
- Suppress mongoDB errors
- Run `npm run test` and all routes including protected routes will pass authentication
[Issue #231](https://github.com/microapidev/comment-microapi/issues/231)

Ft add auth tests

---

__test__/api/comment-delete.test.js
__test__/api/comment-get.test.js
__test__/api/comment-patch.test.js
__test__/api/comment-post.test.js
__test__/api/comment-vote.test.js
__test__/db.test.js
controller/commentsController.js
routes/comments.js

Fixes #235 
Refactor all tests to use global auth tokens and models
- Add auth token to every request header
- Add applicationId to queries from global model
[Issue #235 ](https://github.com/microapidev/comment-microapi/issues/235)
**Questions:**
If something is unclear or you want some questions to be addressed by your peers, mention them here

[refactor]: Refactor all tests to use authentication

---

__test__/api/reply-vote.test.js

Add tests for getting all votes of a comment's reply
**Which issue does this PR solve?**
Fixes issue #219
**Summarise the main tasks handled in the pull request**
Create test suite for 'GET /comments/{commentId}/replies/{replyId}/votes' endpoint
This task creates a test suite to get all votes of a comment's reply
Fork the repo.
Clone your forked repo to you local environment.
In your terminal 'run npm install'
Then run 'npm run test'
[Issue #219 ](https://github.com/microapidev/comment-microapi/issues/219)

[RepliesEndpointTest]-GET /comments/{commentId}/replies/{replyId}/votes (issue #219)

---

__test__/api/comment-patch.test.js
__test__/api/comment-vote.test.js
controller/repliesController.js

Fixes #183 
[Issue #183 ](https://github.com/microapidev/comment-microapi/issues/183)
**Questions:**
If something is unclear or you want some questions to …

[TEST]: PATCH /comments/{commentId}/replies/{replyId}: 

---

utils/validationRules/Replies/flagReplySchema.js

Fixes issue number #239
Summarize the main tasks handled in the pull request
Created a validation schema for flagging a comment/reply within the API
[Issue #239](https://github.com/microapidev/comment-microapi/issues/239)
**Questions:**
If something is unclear or you want some questions to be addressed by your …

Create validation schema to flag a comment/reply

---

controller/commentsController.js
routes/comments.js

Get single comment

---

controller/commentsController.js

Reverts microapidev/comment-microapi#191

Revert "Get single comment"

---

docs/swagger.yaml

Implements the new organizations, admins, and applications endpoints.
- Create `/organizations` endpoints
- Document `/applications` endpoints
- Document `/admins` endpoints
- In your terminal, run `npm start`.
- On your browser, visit `localhost:4000`.
None
None
**Questions:**
None

Swagger docs organizations update

---

controller/commentsController.js

added get singleComment

---

controller/organizationsController.js
package-lock.json
package.json
routes/organizations.js
server.js
utils/auth/passwordUtils.js
utils/auth/tokenGenerator.js

Fixes #268 
Adds endpoint to create a new organization
- Setup password hash and compare utility
- Create controller and route for adding organization
- Create a default admin account right after creating a new organization
- Handle attempt to register duplicate organization emails
- Add error handling to rollback changes in case of errors before completing transaction
- Make a `POST` request to …

[feature]: Create new organization - POST /organizations

---

routes/comments.js
utils/auth/tokenGenerator.js

Generate dummy application tokens when DISABLE_AUTH="true". For testing purposes in the `/comments` route

Hotfix add dummy token

---

__test__/api/__snapshots__/index.test.js.snap
__test__/api/comment-delete.test.js
__test__/api/comment-get.test.js
__test__/api/comment-patch.test.js
__test__/api/comment-post.test.js
__test__/api/comment-vote.test.js
__test__/api/index.test.js
server.js
utils/auth/passwordUtils.js

Update Base route to include 'v1' as versioning

---

__test__/api/comments/delete-comments.test.js
__test__/api/comments/get-comments-id.test.js
__test__/api/comments/get-comments-votes.test.js
__test__/api/comments/get-comments.test.js
__test__/api/comments/patch-comments-flags.test.js
__test__/api/comments/patch-comments-votes.test.js
__test__/api/comments/patch-comments.test.js
__test__/api/comments/post-comments.test.js
__test__/api/replies/delete-replies.test.js
__test__/api/replies/get-replies-id.test.js
__test__/api/replies/get-replies-votes.test.js
__test__/api/replies/get-replies.test.js
__test__/api/replies/patch-replies-flags.test.js
__test__/api/replies/patch-replies-votes.test.js
__test__/api/replies/patch-replies.test.js
__test__/api/replies/post-replies.test.js

The aim is to slowly unskip the tests after fixing both tests and controllers
See #272
Give bullet point instructions on how to setup the code and test it manually (Assume no …

Update tests to skip all but working ones

---

controller/commentsController.js
middleware/auth.js

fixed routes to retrieve dummy data from

---

controller/commentsController.js

Temporary removed  applicationId from Get comments find() method.

Update commentsController.js : [getComments]

---

__test__/api/__snapshots__/index.test.js.snap
__test__/api/index.test.js
docs/swagger.yaml
routes/documentation.js
server.js
utils/swaggerSpec.js

Updates swagger docs for typos and fixes wrong error response object.
- Update orgs `name` and `email` to `organizationName` and `organizationEmail`
- Fix OrganizationResponse schema to return with an object that includes a status property in place of the response property.
- Add endpoint for docs to home route (the home route should have the latest version of the API documentation).
- In your terminal, …

Update swagger docs

---

utils/swaggerSpec.js

It fixes the basePath of the endpoints and updates the description.
- Add more information for description (include links to github and license)
- Replace basePath configuration with servers due to openapi 3 not supporting basePaths.
- In your terminal, run `npm start`
- On your browser, visit `localhost:4000`
None
**What is the link to the issue on …

fix: improve description and add servers for testing

---

controller/commentsController.js
docs/swagger.yaml
utils/swaggerSpec.js

Request bodies were not being recognized and would cause validation middleware to respond with a 422 when using swagger to make requests.
- Update swagger.yaml request bodies to use openapi v3 alternative
- In your terminal, run `npm start`
- On your browser, visit `localhost:4000`
None
None
**Questions:**
None

[FIX] Swagger docs

---

controller/organizationsController.js
models/admins.js
routes/organizations.js

Fixes #297 
Allow admin users generate an organization authentication token to have access to their organization's routes
- Create controller for generating token that accepts an admin's login credentials, email and password, and returns an organization token if validated
Send a POST request to /organizations/token with the sample body
```
{ 
email: "admin@email.com", 
password: ""mysavedPassword, …
```

[feature]: Get organization token - POST /organizations/token

---

controller/adminControllers.js
controller/adminsController.js
middleware/auth.js
routes/admins.js
server.js

Fixes #299 
Create controller for creating new admin account
- Validate request
- Create new admin document
- Hash and store password
- Return adminId
Send a `POST` request to `/admins` with the following sample body structure
and a valid `organizationToken` sent in the bearer token authorization header
```
{
"email": "admin2@email.com",
"password": "mypassword",
"fullname": "I am admin"
}
```
**What is …

[feature]: Create new admin controller

---

controller/adminsController.js
routes/admins.js

Fixes #301 
Create admin controller to retrieve all admin accounts belonging to an organization
- Create controller for getting all admin accounts
- Create route and attach controller 
Send a GET request to `/admins` with a valid organizationToken
[Issue #301](https://github.com/microapidev/comment-microapi/issues/301)

[feature]: Get all admin accounts - GET /admins

---

controller/adminsController.js
routes/admins.js

Fixes #304
Create controller method for an admin to update their details (_currently only fullname_)
- Create updateAdmin controller 
- Add `PATCH /admins` route
Send a PATCH request to `/admins` route with valid `organizationToken` in the Bearer Token authorization header
and sample body 
```
{
"fullname": "The administrator"
}
```
[Issue …

[feature]:  AdminsController - PATCH /admins

---

controllers/adminsController/getSingleAdmin.js
controllers/adminsController/index.js
controllers/commentsController/getAllComments.js
routes/admins.js

Fixes #309 
Create endpoint for getting a single admin account details at GET /admins/{adminId}
- Create controller method to get an admin user
- Attach controller to `GET /admins/{adminId}` route
Make a GET request to `GET /admins/:adminId` with a valid adminId and a valid organizationToken
[Issue #309](https://github.com/microapidev/comment-microapi/issues/3 …

[feature]: AdminsController - GET /admins/{adminId} - Get single admin account

---

controllers/adminsController/changeAdminPassword.js
controllers/adminsController/index.js
routes/admins.js

Fixes #311 
Create controller method to update an admin's user's password
- Create change admin's password controller
- Attach controller to route POST `/admins/change-password` 
Send a POST request to `/admins/change-password` with a valid organizationToken and sample body
```
{
"oldPassword": "newpassword",
"newPassword": "mypassword"
}
```
[Issue …

[feature]: Change admin password - AdminsController - POST /admins/change-password

---

controllers/adminsController/createSingleAdmin.js
controllers/adminsController/deleteSingleAdmin.js
controllers/applicationsController/createSingleApplication.js
controllers/applicationsController/getAllApplications.js
routes/application.js
utils/auth/tokenGenerator.js
utils/validationRules/applications/createApplicationSchema.js
utils/validationRules/applications/deleteApplicationSchema.js
utils/validationRules/applications/getAllApplicationsSchema.js
utils/validationRules/applications/getApplicationTokenSchema.js
utils/validationRules/applications/getSingleApplicationSchema.js
utils/validationRules/applications/updateApplicationSchema.js
utils/validationRules/index.js

Fixes #322 
Create validation rules for all `/applications` endpoints
Validation rules for:
- POST /applications: Endpoint to create an application
- POST /applications/{applicationId}/token: Endpoint to get an application token
- GET /applications: Endpoint to get all applications of organization
- PATCH /applications/{applicationId}: Endpoint to update an application's properties
- DELETE /applications/{applicationId}: Endpoint to delete an …

[feature]: Applications endpoints validations

---

routes/admins.js
utils/validationRules/admins/changeAdminPasswordSchema.js
utils/validationRules/admins/createSingleAdminSchema.js
utils/validationRules/admins/deleteSingleAdminSchema.js
utils/validationRules/admins/getAllAdminsSchema.js
utils/validationRules/admins/getSingleAdminSchema.js
utils/validationRules/admins/updateSingleAdminSchema.js
utils/validationRules/index.js

Fixes #322 
Create validation rules for all `/admins` endpoints
Validation rules for:
- POST /admins: Endpoint to create an admin account
- POST /admins/change-password: Endpoint to change password
- GET /admins: Endpoint to get all admins of organization
- PATCH /admins : Endpoint to update an admin's details
- DELETE /admins/:adminId : Endpoint to delete an admin account
- GET /admins/{adminId}: Endpoint to get an admin account
**How should …

[feature]: Admins endpoints validations

---

controller/applicationController.js
controllers/applicationsController/getApplicationToken.js
controllers/applicationsController/index.js
routes/application.js

Fixes #249 
Add controller for getting an application token
* Add the controller funtion
* Add the route
* Add the router to `server.js`
Uses the `getAppToken` function provided in the `utils` folder, getting the `applicationId` and the `adminId` from the request parameter and body respectively. Protect all application route with `orgAuthMW` middleware. And add the router to `server.js`
visit the `/applications/:applicationId/token` route supplying a valid applicationId (which can be gotten when creating the application) and adminId which can be gotten when creating an admin.
[Issue …

 ApplicationsController - POST /applications/{applicationId}/token

---

routes/application.js

[hotfix]: lint error

---

controllers/applicationsController/getAllApplications.js
controllers/commentsController/createSingleComment.js
controllers/commentsController/deleteSingleComment.js
controllers/commentsController/getAllComments.js
controllers/commentsController/getSingleComment.js
controllers/commentsController/getSingleCommentVotes.js
controllers/commentsController/updateSingleComment.js
controllers/commentsController/updateSingleCommentDownVotes.js
controllers/commentsController/updateSingleCommentFlags.js
controllers/commentsController/updateSingleCommentUpVotes.js
routes/comments.js

- Attach comments to a single application, 
- Remove auth bypass
- Include `organizationId` in applications query

[chore]: refactor comments

---

package-lock.json
package.json
utils/auth/passwordUtils.js

Fixes #329
- Drop bcrypt
- Add bcryptjs
- npm install
- npm run test
#329
Issue #329
**Questions:**

Add bcryptjs as alternative to bcrypt

---

__test__/api/comment-post.test.js
__test__/api/comments/createSingleComment.test.js
controllers/commentsController/createSingleComment.js

Fixes #331 
- missing `content`
- missing `ownerId`
```bash
npm install
npm run test
```
Issue #331 
**Questions:**

[TEST] Add integration tests to create single comment

---

controllers/applicationsController/getSingleApplication.js
controllers/applicationsController/index.js
controllers/applicationsController/updateSingleApplication.js
routes/applications.js

Fixes #263 
Create endpoint to update an application's details
- Create `updateSingleApplication` controller
- Attach controller to PATCH `/applications/:application` route
- Add validation middleware to route
- Send a PATCH request to `/applications/:applicationId` with the following sample body and a valid `organizationToken` and a valid `applicationId` in the url params
```
{
"name": "New app name"
} …
```

[feature]: Update application endpoint - PATCH /applications/{applicationId}

---

__test__/api/comments/createSingleComment.test.js
controllers/commentsController/createSingleComment.js
controllers/commentsController/deleteSingleComment.js
utils/commentHandler.js

Fixes #347
- Add `commentHandler`
- Update `createSingleComment.js` to use `commentHandler`
- Update `createSingleComment.test.js` to use `commentHandler`
- Update `deleteSingleComment.js` to use `commentHandler`
```bash
npm install
npm run test
```
Issue #347
**Questions:**

Add comment handler for uniform endpoint response

---

__test__/api/replies/getAllReplies.test.js
utils/replyHandler.js

Adds a replyHandler that returns a reply DTO.
- Add replyHandler utility function
- Refactor getAllReplies test suite to implement handler.
- In your terminal, run `npm test`.
None
None
**Questions:**
None

Reply handler

---

__test__/utils/commentHandler.test.js

Resolve #355
Fixes #355 
- Unit test for comment handler function
Issue #355
**Questions:**

Add unit test for comment handler

---

__test__/api/comments/getSingleComment.test.js
controllers/commentsController/getSingleComment.js

-  This PR contains test suite that will cover all the functionalities expected from the getSingleComment endpoint
#339 
- checkout to this branch `git checkout …

Chore:  get single comment

---

__test__/api/replies/updateSingleReplyUpVotes.test.js
controllers/repliesController/updateSingleReplyUpVotes.js

- Run npm run lint to find errors in code syntax/format
- Run npm run lint:fix to fix all auto-fixable errors in source code and auto-format with prettier
**DONE**
Fixes [#373 ]
**Summarise the main tasks handled in the pull request**
Implemented a test suite that covers all required functionality expected from the updateSingleReplyUpVotes endpoint /v1/comments/{commentId}/replies/{replyId}/votes/upvote.
Edited controllers/repliesController/updateSingleReplyUpVotes.js to be able to pass the test
In terminal run npm run test
Issue …

 [TEST] updateSingleReplyUpVotes API Endpoint Tests

---

controllers/repliesController/updateSingleReplyDownVotes.js

Fix error causing tests to fail, missing `await` keyword

hotfix: failing tests on Travis CI

---

__test__/api/applications/updateSingleApplication.test.js
controllers/applicationsController/updateSingleApplication.js

Fixes #388 
Fixes #390 
**Questions:**
There's no entry on the sheet for test the PATCH /applications/:applicationId route

fix update application and create tests

---

__test__/api/replies/getSingleReply.test.js
controllers/repliesController/getSingleReply.js

- This PR contains test suite that will cover all the functionalities expected from the getSingleReply endpoint
#370 
1. - checkout to this branch `git checkout chore-getSingle-Reply`
2. - run `npm install`
3. - run `npm run test` …

chore: added test for getting single reply

---

__test__/api/replies/createSingleReply.test.js
controllers/repliesController/createSingleReply.js
utils/replyHandler.js

Resolve #366 
```bash
npm install
npm run test
```
Issue #366 
**Questions:**

Test update create reply

---

__test__/api/admins/changePassword.test.js
__test__/config/setup.js

Admin password change tests

---

__test__/api/applications/deleteSingleApplication.test.js
controllers/applicationsController/deleteSingleApplication.js

Fixes #398 
[Issue #398 ](https://github.com/microapidev/comment-microapi/issues/14) …

[Test]: add test for deleteSingleApplication endpoint

---

__test__/api/applications/getAllApplications.test.js
controllers/applicationsController/getAllApplications.js
docs/swagger.yaml

Fixes #407 
This PR implements a test suite that will cover all required functionality expected from the getAllApplications endpoint /v1/applications. For each test that doesn't pass, the controller method (along with its validation schema and swagger docs if the modifications require it) will be modified to include the required functionalities so that the test passes.
- In your terminal, run `npm test` …

[TEST] getAllApplications API Endpoint

---

docs/swagger.yaml

docs: remove organizationId as a required property

---

__test__/api/admins/getAllAdmins.test.js
controllers/adminsController/getAllAdmins.js
models/applications.js
package.json
utils/errorhandler.js

Fixes #417 
Implement tests for `getAllAdmins` controller at `GET /admins` endpoint
- Implement test
- Add unique index to application name  in schema
- Include detailed errors when running in `dev` or `test` environment 
Run `npm run test __test__/api/admins/getAllAdmins.test.js`

[TEST] - Get all admins test - GET /admins

---

__test__/api/comments/getAllComments.test.js
__test__/api/comments/updateSingleComment.test.js
__test__/api/replies/updateSingleReply.test.js
__test__/api/replies/updateSingleReplyUpVotes.test.js
controllers/commentsController/getAllComments.js
controllers/commentsController/getSingleComment.js
controllers/commentsController/updateSingleComment.js
controllers/repliesController/getAllReplies.js
controllers/repliesController/getSingleReply.js
controllers/repliesController/getSingleReplyVotes.js
controllers/repliesController/updateSingleReply.js
docs/swagger.yaml
models/replies.js
utils/commentHandler.js
utils/replyHandler.js

Fixes #423 
-
None
[Issue #423](https://github.com/microapidev/comment-microapi/issues/423)
**Questions:**
No question

[hotfix]: Add timestamps to comments and replies responses

---

__test__/utils/settings.test.js
models/msadmins.js
models/systemSettings.js
utils/auth/tokenGenerator.js
utils/settings.js

Fixes #426 
Setup models and utilities for microservice admins
- Create MsAdmin model
- Create SystemSettings model and ENV variables setter utility
- Add System Token generator
Run `npm run test`

Setup models and utilities for microservice admins

---

__test__/api/msadmins/loginAdmin.test.js
__test__/config/setup.js
controllers/msAdminsController/index.js
controllers/msAdminsController/loginSysAdmin.js
routes/msadmins.js
utils/validationRules/index.js
utils/validationRules/msadmins/index.js
utils/validationRules/msadmins/loginAdminSchema.js

Fixes #432
Endpoint for msAdmins to login
- Write tests for logging in microservice admins endpoint
- Exclude route from authentication middleware
- Create controller for logging in microservice admins
- Send POST request to `/v1/msadmins/login` with the sample body
```
{
"email": "email@domain.com",
"password": "password",
}
```

[feature]: Microservice Admins login - POST /msadmins/login

---

__test__/api/msadmins/getSingleMsAdmin.test.js
__test__/api/replies/updateSingleReplyUpVotes.test.js
__test__/config/setup.js
__test__/utils/auth/msadmin.test.js
controllers/commentsController/getAllComments.js
controllers/commentsController/updateSingleComment.js
controllers/msAdminsController/getSingleMsAdmin.js
controllers/msAdminsController/index.js
controllers/repliesController/getAllReplies.js
controllers/repliesController/updateSingleReply.js
routes/msadmins.js
utils/auth/msadmin.js
utils/commentHandler.js
utils/replyHandler.js
utils/validationRules/msadmins/getSingleMsAdminSchema.js
utils/validationRules/msadmins/index.js

Fixes #438 
An endpoint to get a single microservice admin
- Create controller for getting single admin
- Fix timestamps format
- Send GET request to `/v1/msadmins/:msAdminId` with a valid superAdmin system token
Only superAdmins can access this endpoint

[feature]: Get single microservice admin - GET/msadmins/:msAdminId

---

controllers/msAdminsController/index.js
controllers/msAdminsController/updateSingleMsAdmin.js
routes/msadmins.js
utils/validationRules/msadmins/index.js
utils/validationRules/msadmins/updateSingleMsAdminSchema.js

Fixes #440 
An endpoint for a microservice admin to update their details
- Create controller to update detials
- Send PATCH request to `/v1/msadmins` with a valid msadmin system token and sample body
```
{
"fullname": "Say my name"
}
```

[feature]: update microservice admin details

---

__test__/api/msadmins/updateSingleMsAdmin.test.js
controllers/msAdminsController/updateSingleMsAdmin.js

Complements #440 
This commit which contains tests was missed in the last commit to PR

[hotfix]: add update single msadmin tests

---

__test__/api/msadmins/settings/getSystemSettings.test.js
controllers/msAdminsController/settings/getSystemSettings.js
controllers/msAdminsController/settings/index.js
routes/msadmins/index.js
routes/msadmins/settings.js
utils/validationRules/msadmins/index.js
utils/validationRules/msadmins/settings/getSystemSettingsSchema.js

Fixes #448 
An endpoint to get all microservice settings
- Create controller for getting all system settings
- Send GET request to `/v1/msadmins/settings` with a valid superAdmin system token
Only superAdmins can access this endpoint

[feature]: Get all microservice system settings - GET /msadmins/settings

---

__test__/api/comments/updateSingleCommentUpVote.test.js
__test__/api/msadmins/organizations/getOrganizationApps.test.js
__test__/api/msadmins/settings/updateSystemSettings.test.js
bin/www.js
controllers/msAdminsController/organizations/getOrganizationsApps.js
controllers/msAdminsController/organizations/index.js
controllers/msAdminsController/settings/index.js
controllers/msAdminsController/settings/updateSystemSettings.js
middleware/validation.js
models/systemSettings.js
routes/msadmins/applications.js
routes/msadmins/index.js
routes/msadmins/organizations.js
routes/msadmins/settings.js
utils/validationRules/msadmins/index.js
utils/validationRules/msadmins/organzationsSchema/getOrganizationsApps.js
utils/validationRules/msadmins/settings/updateSystemSettingsSchema.js

Fixes #457 
An endpoint to update microservice settings
- Initialize settings on startup of microservice
- Create controller for update system settings
- Send PATCH request to `/v1/msadmins/settings` with a valid superAdmin system token and valid system settings in the body of the request
**Any background …

[feature]: Update system settings

---

__test__/api/msadmins/applications/blockSingleApplication.test.js
controllers/msAdminsController/applications/blockSingleApplication.js
controllers/msAdminsController/applications/index.js
models/applications.js
routes/msadmins/applications.js
utils/validationRules/msadmins/applicationsSchema/blockApplicationSchema.js
utils/validationRules/msadmins/applicationsSchema/blockSingleApplicationSchema.js
utils/validationRules/msadmins/index.js

Fixes #460  (replace issue_number with the issue number this PR solves)
None
[Issue #460 ](https://github.com/microapidev/comment-microapi/issues/460)
**Questions:**
If something is unclear or …

Feat: Add endpoint to block an application using the service

---

__test__/api/comments/updateSingleCommentUpVote.test.js
__test__/api/msadmins/applications/unblockSingleApplication.test.js
__test__/api/msadmins/organizations/unblockSingleOrganization.test.js
controllers/msAdminsController/applications/index.js
controllers/msAdminsController/applications/unblockSingleApplication.js
controllers/msAdminsController/organizations/unblockSingleOrganization.js
routes/msadmins/applications.js

Fixes #460  (replace issue_number with the issue number this PR solves)
None
[Issue #462 ](https://github.com/microapidev/comment-microapi/issues/462)
**Questions:**
If something is unclear or …

Feat: Endpoint to allow unblocking of applications

---

__test__/api/msadmins/applications/deleteSingleApplication.test.js
controllers/msAdminsController/applications/deleteSingleApplication.js
controllers/msAdminsController/applications/index.js
routes/msadmins/applications.js
utils/validationRules/msadmins/applicationsSchema/deleteApplicationSchema.js
utils/validationRules/msadmins/index.js

Fixes #464 (replace issue_number with the issue number this PR solves)
None
[Issue #464 ](https://github.com/microapidev/comment-microapi/issues/464)
**Questions:**
If something is unclear or …

Feat: Endpoint to allow msadmin delete application

---

__test__/api/msadmins/organizations/getAllOrganizations.test.js
controllers/msAdminsController/organizations/getAllOrganizations.js
controllers/msAdminsController/organizations/index.js
routes/msadmins/organizations.js
utils/validationRules/msadmins/index.js
utils/validationRules/msadmins/organzationsSchema/getAllOrganizationsSchema.js

Fixes #466  (replace issue_number with the issue number this PR solves)
None
[Issue #466  ](https://github.com/microapidev/comment-microapi/issues/466)
**Questions:**
If something is unclear or …

Feat: Endpoint for msadmin to get all organizations

---

__test__/api/msadmins/organizations/getSingleOrganization.test.js
controllers/msAdminsController/organizations/getSingleOrganization.js
controllers/msAdminsController/organizations/index.js
routes/msadmins/organizations.js

Fixes #468   (replace issue_number with the issue number this PR solves)
None
[Issue #468  ](https://github.com/microapidev/comment-microapi/issues/468)
**Questions:**
If something is unclear …

Feat: Endpoint for msadmins to get a single organization

---

controllers/msAdminsController/createSingleMsAdmin.js
docs/swagger.yaml
utils/swaggerSpec.js

[Docs] Update Swagger docs to include Ms Admin Mgt Enpoints

---

__test__/api/msadmins/applications/blockSingleApplication.test.js
controllers/msAdminsController/applications/blockSingleApplication.js
docs/swagger.yaml

Fixes #472  (replace issue_number with the issue number this PR solves)
Any pertinent …

Doc: Update swagger docs to include Orgs, Apps and Settings endpoints

---

controllers/msAdminsController/organizations/getAllOrganizations.js

Updates the variable and property names of the getAllOrganizations controller to be in line with the swagger documentation. 
- Rename the variable from the mapped function from `organizations` to `organization`. (As it is only one organization, it should be singular).
- Rename one of the returned object's property from `organizationsName` to `organizationName`. (To be in line with the swagger documentation.
**How should this be manually …

fix: update variable and property names

---

__test__/api/subscriptions/subscribeSingleApplication.test.js
controllers/subscriptionsController/index.js
controllers/subscriptionsController/subscribeSingleApplication.js
models/subscriptions.js
routes/applications.js
utils/validationRules/index.js
utils/validationRules/subscriptions/subscribeSingleApplication.js

Fixes #479 (replace issue_number with the issue number this PR solves)
Added Endpoint for applications to subscribe to using the service …

Feat: Endpoint to Subscribe and application

---

__test__/api/msadmins/organizations/deleteSingleOrganization.test.js
__test__/api/msadmins/organizations/unblockSingleOrganization.test.js
__test__/middleware/requestLogger.test.js
middleware/requestLogger.js
models/requestLogs.js
utils/auth/tokenGenerator.js

Fixes #488 
Create an applications' requests logger
- Create request logger model
- Create log writer 
- Create request log writing middleware with support for system settings and application plans
- Write relevant tests
- The middleware requires systemSetting,  `loggingEnabled` to be `true`
- The application setting also requires `loggingEnabled` to be true on a `logging` plan

[feature]: Add applications' requests logger

---

__test__/api/applications/getAllPlans.test.js
__test__/api/msadmins/plans/createNewPlan.test.js
__test__/api/msadmins/plans/getAllPlans.test.js
controllers/msAdminsController/plans/createNewPlan.js
controllers/msAdminsController/plans/getAllPlans.js
controllers/msAdminsController/plans/index.js
controllers/subscriptionsController/subscribeSingleApplication.js
routes/applications.js
routes/msadmins/plans.js
utils/validationRules/applications/getAllPlansSchema.js
utils/validationRules/index.js

Fixes #492 
[Issue #14](https://github.com/microapidev/comment-microapi/issues/14)
**Questions:**
If something is unclear or you want some …

Feat-Applications: GET /applications/plans

---

__test__/api/msadmins/plans/deleteSinglePlan.test.js
controllers/msAdminsController/plans/deleteSinglePlan.js
controllers/msAdminsController/plans/getAllPlans.js
controllers/msAdminsController/plans/index.js
controllers/subscriptionsController/getSingleAppSubscription.js
controllers/subscriptionsController/subscribeSingleApplication.js
routes/msadmins/plans.js
utils/validationRules/msadmins/index.js
utils/validationRules/msadmins/planSchema/plansSchema.js

Fixes #494 
- Create endpoint for use by msadmins
[Issue #494 ](https://github.com/microapidev/comment-microapi/issues/494)
**Questions:**
If …

Feat: Msadmin endpoint to delete a plan ... DELETE /msadmins/plans/:planId

---

__test__/api/msadmins/plans/getSInglePlan.test.js
controllers/msAdminsController/plans/getSinglePlan.js
controllers/msAdminsController/plans/index.js
routes/msadmins/plans.js

Fixes #496 
[Issue #496 ](https://github.com/microapidev/comment-microapi/issues/496)
**Questions:**
If something is unclear or you want some …

Feat: msadmin get single plan

---

__test__/api/subscriptions/getAllAppSubscriptions.test.js
controllers/subscriptionsController/getAllAppSubscriptions.js
controllers/subscriptionsController/index.js
docs/swagger.yaml
routes/msadmins/applications.js

Fixes #477  (replace issue_number with the issue number this PR solves)
**What is the link …

Feat: Endpoint for msadmin to get all susbcriptions

---

utils/validationRules/msadmins/settings/updateSystemSettingsSchema.js

Resolve #506
Fix #506
- add missing validation rules
Issue #506
**Questions:**

bug: fix msadmins system settings update

---

docs/swagger.yaml

Fixes #509  (replace issue_number with the issue number this PR solves)
Any pertinent …

Update: swagger docs 
