routes/comments.js, server.js
ES6 syntax is causing the app to crash on heroku since we are not using babel-node in production. This has been removed temporarily until the app is refcactored to accommodate building ES6 modules
=> hotfix: temporarily remove es6 syntax

controller/commentsController.js, routes/comments.js
- This PR contains the controller and route for a user to flag off a comment by its ID and increment it in the database as described in the documentation
- I am available for any tasks related or unrealted to this
- this can be tested by hitting the endpoint `/comments/{commentID}/flag ` with a **patch** http …
=> feat: added the functionality for users to fag off comments

utils/validationRules.js
- Uses the @hapi/joi npm package to define a schema of Javascript objects.
- Uses Joi's handy methods that come bundled with it, to validate any relevant params, body, query, or headers against the schema.
Additionally, the @hapi/joi package also creates detailed error messages for us so we don't have to write error messages again and again for every case.
The tests will only be possible once the routes …
=> feat: add validation rules for endpoints

__test__/api/comment-vote.test.js
Add tests for upvoting and downvoting comments endpoint
running `npm test` should display the written test
I will like to return to this test when getting a comment is implemented. I'm only testing that the returned value satisfy the spec. I will like to get the comment and verify that the vote is incremented or decremented accordingly
[Issue …
=> write tests for downvote and upvote of comments (#75)

docs/swagger.yaml
Adds the missing `GET /comments/{commentId}/replies/{replyId}` endpoint to the swagger docs.
Update the swagger.yaml file to include the missing endpoint.
- On you terminal, run `npm start`
- Visit `localhost:4000` or `localhost:4000/documentation`
None
[Issue …
=> feat: add get endpoint for a reply

__test__/api/comment-vote.test.js
Continues PR #98  Issue #75 
* Match specification
* Ensure the number of votes returned is correct
* Inserts a comment into the database, and visit the upvote route, then check that the total number of votes and the total number of upvotes are both equal to 1 and total number of downvote is 0
* Inserts a comment into the database and visit the downvote route, then check that the number of votes returned is as expected
I had already written the tests when upvote and downvote were separate routes. 
**What is the link to …
=> CommentsEndpointTests - PATCH /comments/{commentId}/votes/*: Refactor comment upvote and downvote test suite to match new spec

__test__/api/comment-delete.test.js, controller/repliesController.js, routes/replies.js
Fixes #126 
* Write the controller for deleting replies
* Add the route
* Fix the test
Delete the reply matching the `replyId`, `commentId`, and `ownerId` from the database, remove the reply from the list of replies for the comment. Return the deleted reply.
Run `npm test -- -t "DELETE /comments/:commentId/replies/:replyId"` to see the test for the route pass
[Issue #126 ](https://github.com/microapidev/comment-microapi/issues/126)
=>  RepliesController - DELETE /comments/{commentId}/replies/{replyId}

__test__/api/comment-patch.test.js, middleware/validation.js, routes/comments.js, routes/replies.js, utils/validationRules/comments/createCommentSchema.js, utils/validationRules/comments/getAllCommentsSchema.js, utils/validationRules/comments/getCommentVotesSchema.js, utils/validationRules/comments/getSingleCommentSchema.js, utils/validationRules/comments/updateCommentSchema.js, utils/validationRules/index.js
Fixes #182 
There were fixes to the validation middleware as it did not work due to how errors were created by joi (they never got thrown so they could never reach the catch block) and the validate function (it doesn't return a promise so the then function did not exist). 
The schemas also had to have their header property renamed to headers so that it could match on one of the schemaKeys in the validation middleware.
- Creates validation …
=> Get comment votes validation schema

utils/validationRules/comments/updateCommentUpAndDownVoteSchema.js, utils/validationRules/index.js
Fixes #200 
The PR implements for 2 endpoints as they have the same validation schema.
- Add validation schema for updating upvotes
- Use the same validation schema for downvotes
Endpoints need to implement validation middleware first.
None
[Issue …
=> feat: add validation schema for updating comment votes

utils/validationRules/Replies/updateReplyUpAndDownVoteSchema.js, utils/validationRules/index.js
Fixes #203 
The PR implements for 2 endpoints as they have the same validation schema.
- Add validation schema for updating upvotes
- Use the same validation schema for downvotes**How should this be manually tested?**
Endpoints need to implement validation middleware first.
None
[Issue #203 ](https://github.com/microapidev/comment-microapi/issues/203) …
=> feat: add validation schema for up and down vote endpoint

__test__/api/comment-patch.test.js, middleware/validation.js, routes/comments.js
It is a hotfix for the current Application Error on the heroku servers due to integration with ES6 modules not working. The fix changes imports in validation.js middleware to require. 
- Change import to require instead
None
None
None
**Questions:**
None
=> fix: change the import to use require instead

.eslintrc.js
Add eslint rule to suppress end of line errors where eol is CRLF.
EOL defaults to LF for my device, not sure why. But this update sets EOL to auto which makes it use CRLF for Windows and LF for other devices.
Add rule
```javascript
"prettier/prettier": [
"error",
{
endOfLine: "auto",
},
],
```
**Questions:**
=> Update eslint config to suppress eol errors

utils/validationRules/index.js
Ensures that the validation schema (rules) of updating a reply are made available through the index file in the utils/validationRules folder.
Includes the validation schema for updating a reply the utils/validationRules/Replies/updateReplySchema.js by requiring and exporting it in the utils/validationRules/index.js file.
Give bullet point instructions on how to setup the code and test it manually …
=> [FIX] Include updateReplySchema in index.js

__test__/api/comment-patch.test.js
Add tests for flagging the reply to a comment
* save a test comment and a test reply
* then send a requst to the reply flagging route
* test that the returned number of flags is 1
[Issue #222 ](https://github.com/microapidev/comment-microapi/issues/222)
=> [TEST] RepliesEndpointTests - PATCH /comments/{commentId}/replies/{replyId}/flag (#222)

middleware/auth.js
The `DISABLE_AUTH` environment variable is a boolean variable that is used to temporarily disable authentication in guarded routes. This is read in as string and the value needs to be cast to its true boolean value.
- Check string value of `DISABLE_AUTH` and convert it to its equivalent boolean value
- Toggling `DISABLE_AUTH` should no have the desired effects
**What is the link to the issue on …
=> [hotfix]: fix bug in boolean environment variables

controller/repliesController.js
The current implementation for returning replies is returning a response body not in line with docs. Update the data format of the response in the controller method to get all replies.
- Update the data format of the response in the controller method to get all replies.
- In your terminal, run `npm start`
- Using postman or similar, make a GET `http://localhost:4000/v1/comments/5efb3451ed62e216f8c0a5a1/r …
=> fix: return the correct format on endpoint to get all replies

__test__/api/comment-get.test.js, controller/repliesController.js
The current implementation is returning the wrong format when getting a single reply. An update the format on the controller method ensures that the method returns a format in line with the docs.
- Update the format on the controller method for getting a single reply to be in line with the documentation
- In your terminal, run `npm start`
- On postman or similar, make a GET …
=> fix: update response format on endpoint to get a reply

controller/commentsController.js, controller/repliesController.js, docs/swagger.yaml, utils/validationRules/Replies/createReplySchema.js, utils/validationRules/Replies/deleteReplySchema.js, utils/validationRules/Replies/getReplyVotesSchema.js, utils/validationRules/Replies/getSingleReplySchema.js, utils/validationRules/comments/createCommentSchema.js, utils/validationRules/comments/getCommentVotesSchema.js, utils/validationRules/comments/updateCommentSchema.js
Fixes a few issues with the validation schema and controller methods. It also updates the docs to be more clear.
- Update the votes schemas to ensure that only `downvote` and `upvote` are accepted as valid.
- Update the votes controller methods to ensure that they can be compared with a string by first casting it to a string.
- Update the docs to only accept two options for voteType query parameter.
- …
=> [FIX] Update the votes validation schema and controller methods for comments and replies votes' GET requests.

__test__/api/__snapshots__/index.test.js.snap, __test__/api/index.test.js, controllers/adminsController/changeAdminPassword.js, controllers/adminsController/getSingleAdmin.js, routes/documentation.js, server.js
Fixes #315 
Swagger docs does not display on `/v1/documentation` route
Fix routing to display swagger docs on `/`, `v1`, `/v1/documentation`
Visit `/v1/documentation` and other roues specified above should display swagger docs
[Issue #315 ](https://github.com/microapidev/comment-microapi/issues/315)
=> bug: fix swagger docs router

__test__/api/comment-get.test.js, __test__/api/replies/getAllReplies.test.js, controllers/repliesController/getAllReplies.js
Fixes #332 
This PR implements a test suite that will cover all required functionality expected from the getAllReplies endpoint /v1/comments/{commentId}/replies. For each test that doesn't pass, the controller method (along with its validation schema and swagger docs if the modifications require it) will be modified to include the required functionalities so that the test passes.
- In your terminal, run …
=> [FIX] getAllReplies API Endpoint Test

__test__/api/comments/getAllComments.test.js, __test__/api/replies/getAllReplies.test.js, controllers/commentsController/getAllComments.js
Fixes #336 
This PR implements a test suite that will cover all required functionality expected from the getAllComments endpoint /v1/comments. For each test that doesn't pass, the controller method (along with its validation schema and swagger docs if the modifications require it) will be modified to include the required functionalities so that the test passes.
- In your terminal, run `npm test`
**Any …
=> [FIX] getAllComments API Endpoint Tests

__test__/api/comment-patch.test.js, __test__/api/comments/updateSingleComment.test.js, docs/swagger.yaml, routes/comments.js, utils/validationRules/comments/updateSingleCommentSchema.js, utils/validationRules/index.js
Fixes #346 
This PR implements a test suite that will cover all required functionality expected from the updateSingleComment endpoint /v1/comments/{commentId}. For each test that doesn't pass, the controller method (along with its validation schema and swagger docs if the modifications require it) will be modified to include the required functionalities so that the test passes.
- In your terminal, run …
=> [FIX] updateSingleComment API Endpoint Tests

__test__/api/comments/deleteSingleComment.test.js, controllers/commentsController/deleteSingleComment.js
Resolve #341
- test status 200 success
- test status 404 commentId not found/invalid
- test status 422 ownerId missing in request
- test status 401 unauthorized request
- update delete comments controller as required
```bash
npm install
npm run test
```
Issue #341
**Questions:**
=> Add integration test for delete comment endpoint

__test__/api/replies/updateSingleReply.test.js, controllers/repliesController/updateSingleReply.js, docs/swagger.yaml
Fixes #354 
This PR implements a test suite that will cover all required functionality expected from the updateSingleReply endpoint /v1/comments/{commentId}/replies/{replyId}. For each test that doesn't pass, the controller method (along with its validation schema and swagger docs if the modifications require it) will be modified to include the required functionalities so that the test passes.
- In your …
=> [FIX] updateSingleReply API Endpoint Tests

__test__/api/organizations/getSingleOrganizationToken.test.js, controllers/organizationsController/getSingleOrganizationToken.js
Fixes #350 
Adds tests for getting organization token
Correct status code in the controller
[Issue #350](https://github.com/microapidev/comment-microapi/issues/350)
**Questions:**
* In the spec, `organizationEmail` is part of the body, but `email` is being checked while validating, this caused some confusion for me, but I figured the spec was not updated.
* Also the spec specified 401 as the status code for authentication error, but 400 was being sent, I changed this to 401 because I think the spec is more correct here
* The spec also specified 201 as the status code for a successful operation, but the code is sending 200, I wasn't sure which was correct here, so I left it like that and tested for 200.
=> fixes #350: getSingleOrganizationToken.test.js

controllers/repliesController/createSingleReply.js, controllers/repliesController/deleteSingleReply.js, controllers/repliesController/getAllReplies.js, controllers/repliesController/getSingleReply.js, controllers/repliesController/getSingleReplyVotes.js, controllers/repliesController/updateSingleReply.js, controllers/repliesController/updateSingleReplyDownVotes.js, controllers/repliesController/updateSingleReplyFlags.js, controllers/repliesController/updateSingleReplyUpVotes.js, routes/replies.js, utils/validationRules/index.js, utils/validationRules/replies/updateReplyFlagSchema.js
Fixes #364 
Modify all replies controllers to check that a reply's parent comment belongs to the requesting application
- Add `replyFlagSchema` validation rule and middleware
- Add condition checking that a reply's parent comment belongs to the requesting application
Attempt to get a reply belonging to a different application will result in a 404 error
=> [Fix]: Link replies' controllers to application

__test__/api/replies/getSingleReplyVotes.test.js, __test__/api/replies/updateSingleReply.test.js, utils/swaggerSpec.js
Fixes #403 
This PR implements a test suite that will cover all required functionality expected from the getAllReplies endpoint /v1/comments/{commentId}/replies. For each test that doesn't pass, the controller method (along with its validation schema and swagger docs if the modifications require it) will be modified to include the required functionalities so that the test passes.
- In your terminal, run …
=> [TEST] getSingleReplyVotes API Endpoint Tests

.env.example, .travis.yml, __test__/api/msadmins/createSingleMsAdmin.test.js, __test__/config/setup.js, __test__/utils/auth/msadmin.test.js, bin/www.js, controllers/msAdminsController/createSingleMsAdmin.js, controllers/msAdminsController/index.js, middleware/auth.js, routes/msadmins.js, server.js, utils/auth/msadmin.js, utils/auth/tokenGenerator.js, utils/validationRules/index.js, utils/validationRules/msadmins/createSingleMsAdminSchema.js
Fixes #428 
Create endpoint for creating microservice admins and supporting utilities
- Create functionality to create a default super admin for microservice when none is found from ENV variables
- Write tests for creating microservice admins endpoint
- Create authentication middleware for microservice administration routes
- Create controller for creating microservice admins …
=> [feature]: Create microservice admins - POST /msadmins/create

__test__/api/comments/getAllComments.test.js, __test__/api/organizations/deleteSingleOrganization.js, __test__/api/pagination.test.js, __test__/api/replies/getAllReplies.test.js, controllers/commentsController/getAllComments.js, controllers/organizationsController/deleteSingleOrganization.js, controllers/organizationsController/index.js, controllers/repliesController/getAllReplies.js, docs/swagger.yaml, middleware/pagination.js, models/comments.js, models/replies.js, package-lock.json, package.json, routes/comments.js, routes/organizations.js, routes/replies.js, utils/validationRules/organizations/deleteOrganizationSchema.js
Fixes #430 
- If PR is merged: 
`https://comments-microservice.herokuapp.com/comments/?page=2&limit=2`
[Issue #430](https://github.com/microapidev/comment-microapi/issues/430)
**Questions:**
If something is …
=> [feature]: setup pagination on `GET /comments & GET .../replies` endpoints

__test__/api/msadmins/getAllMsAdmins.test.js, __test__/config/setup.js, controllers/msAdminsController/getAllMsAdmins.js, controllers/msAdminsController/index.js, middleware/auth.js, routes/msadmins.js, utils/validationRules/msadmins/getAllMsAdminsSchema.js, utils/validationRules/msadmins/index.js
Fixes #436 
An endpoint to get all microservice admins
- Create controller for getting all system admins
- Send GET request to `/v1/msadmins` with a valid superAdmin system token
Only superAdmins can access this endpoint
=> [feature]: Get all microservice admins - GET /msadmins

__test__/api/msadmins/enableDisableMsAdmin.test.js, controllers/msAdminsController/enableDisableMsAdmin.js, controllers/msAdminsController/index.js, models/msadmins.js, package-lock.json, package.json, routes/msadmins.js, utils/softDelete.js, utils/validationRules/msadmins/createSingleMsAdminSchema.js, utils/validationRules/msadmins/enableDisableMsAdminSchema.js, utils/validationRules/msadmins/index.js
An endpoint to disable microservice admins
- Prepare soft-delete utility
- Create controller disabling system admins
- Create controller enabling system admins
- Attach controller to the routes
- Write tests for the endpoints
- Send PATCH request to `/v1/msadmins/:msAdminId/disable` with a valid superAdmin system token to disable msAdmin
- Send PATCH request to …
=> [feature]: Disable/Enable microservice admins => PATCH /msadmins/:msAdminId/enable~disable

__test__/utils/auth/msadmin.test.js, utils/auth/msadmin.js
For system setups where no .ENV variable is set, for now we are making this temp bypass and assigning default values to the superadmin account. Should be removed in future releases
=> [hotfix]: temp default superadmin email and password

__test__/api/admins/createSingleAdmin.test.js, __test__/api/comments/updateSingleCommentUpVote.test.js, __test__/api/msadmins/applications/unblockSingleApplication.test.js, __test__/api/msadmins/organizations/blockSingleOrganization.test.js, __test__/api/msadmins/organizations/getOrganizationApps.test.js, __test__/api/msadmins/settings/updateSystemSettings.test.js, __test__/config/db.js, __test__/config/setup.js, __test__/db.test.js, __test__/middleware/globalRateLimiter.test.js, __test__/middleware/planRatesLimiter.test.js, bin/www.js, controllers/commentsController/updateSingleCommentDownVotes.js, controllers/commentsController/updateSingleCommentUpVotes.js, db/database.js, middleware/globalRateLimiter.js, middleware/planRatesLimiter.js, models/systemSettings.js, package-lock.json, package.json, routes/comments.js, server.js, utils/auth/msadmin.js, utils/dbParams.js, utils/settings.js
Fixes #474 
Add request rate limits on the application and system levels
- Add global rates limiter (maximum requests per minute) middleware and write tests to prevent DDoS
- Add plans rates limiter (maximum requests per day) middleware and write tests
- Add global rate limit for all requests to system settings
- Add default rate limit for plans to system settings
- Add system setting to disable all request rates limiting
**How should this be …
=> [feature]: Create request limit middleware

__test__/api/applications/getSingleApplicationLog.test.js, __test__/api/msadmins/applications/deleteSingleApplication.test.js, __test__/api/msadmins/getAllMsAdmins.test.js, __test__/middleware/requestLogger.test.js, controllers/applicationsController/getSingleApplicationLog.js, controllers/applicationsController/index.js, controllers/msAdminsController/applications/index.js, middleware/requestLogger.js, models/requestLogs.js, routes/applications.js, routes/comments.js, routes/msadmins/applications.js, settingAndVariables.txt, utils/dateTImeUtils.js, utils/validationRules/applications/getSingleApplicationLogSchema.js, utils/validationRules/index.js
Fixes #499
Endpoints should be available for admin user or msAdmin user to be able to get logs of an application's requests
- Create controller to get a single application's logs
- Create validation rule
- Apply validation middleware
- Attach route and validation to controller
- Refactor controller to work with both admins and MsAdmins
Make a GET request to `/msadmins/applications/:applicationId/log` …
=> [feature]: Get request logs for single application endpoints

controllers/msAdminsController/organizations/getAllOrganizations.js, controllers/msAdminsController/organizations/getSingleOrganization.js, docs/swagger.yaml
It includes the email property of organizations in the response body for msadmins GET requests.
In your terminal, run `npm start`.
- On postman, with the correct system admin token, make a GET to the endpoints.
This will allow the admin dashboard to be able to show the emails of organizations.
None …
=> feat: add email to response body of get organization(s)
